apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
    env: {{ .Values.appEnv }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        env: {{ .Values.appEnv }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 3000

        env:
        - name: APP_ENV
          value: {{ .Values.appEnv | quote }}
        - name: APP_VERSION
          value: {{ .Values.image.tag | quote }}
        - name: PORT
          value: "3000"

        # ArgoCD watches these probes to mark app Healthy
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3

        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            cpu:    {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu:    {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
